[package]
name = "firmware"
version = "0.1.0"
edition = "2018"

[dependencies]
feather_m0 = { version = "0.9.0", features = ["unproven"]}
embedded-hal = "0.2.3"
bitbang-hal = "0.3.2"
cortex-m-rt = "0.6"
cortex-m = "0.6"
panic-halt = "0.2"
smart-leds = "0.3"
smart-leds-trait = "0.2"
apa102-spi = "0.3"
ws2812-spi = {version = "0.4.0",  features = ["mosi_idle_high"]}

[[bin]]
name = "firmware"
test = false
bench = false

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"

